name: "Bandit Security Scan"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  bandit:
    name: Run Bandit
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -r elo_calculator.py elo_model.py elo_simulator.py elo_storage.py test_elo_model.py test_elo_theme.py
